services:
  cassandra:
    image: 'cassandra:latest'
    environment:
      - 'CASSANDRA_DC=dc1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
    ports:
      - '9042'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  wiremock:
    image: wiremock/wiremock:2.32.0
    ports:
      - 9000:8080
    volumes:
      - ./wiremock/:/home/wiremock
